export const flights = [
  {
    airlineCode: "WY",
    route: "MCT-HKT",
    flightNumber: "WY831",
    type: "J",
    date: "Sep 09",
    departure: "09:30",
    arrival: "19:00",
    depStation: "MCT",
    arrStation: "HKT",
    status: "Scheduled",
    acType: "B737",
    acReg: "A9C-BA",
    groundTime: "1h 20m",
    plan: "Meal Plan A",
    paxTotal: 180,
    pax: {
      first: "10/12",
      business: "20/24",
      premium: "25/30",
      economy: "125/150",
    },
  },
  {
    airlineCode: "EK",
    route: "DXB-LHR",
    flightNumber: "EK001",
    type: "F",
    date: "Sep 10",
    departure: "14:15",
    arrival: "18:45",
    depStation: "DXB",
    arrStation: "LHR",
    status: "On Time",
    acType: "A380",
    acReg: "A6-EUZ",
    groundTime: "2h 30m",
    plan: "Meal Plan B",
    paxTotal: 525,
    pax: {
      first: "14/14",
      business: "76/76",
      premium: "56/56",
      economy: "379/379",
    },
  },
  {
    airlineCode: "QR",
    route: "DOH-JFK",
    flightNumber: "QR701",
    type: "J",
    date: "Sep 09",
    departure: "08:00",
    arrival: "14:20",
    depStation: "DOH",
    arrStation: "JFK",
    status: "Departed",
    acType: "A350",
    acReg: "A7-ALN",
    groundTime: "3h 00m",
    plan: "Meal Plan C",
    paxTotal: 312,
    pax: {
      first: "0/0",
      business: "36/36",
      premium: "0/0",
      economy: "276/283",
    },
  },
  {
    airlineCode: "BA",
    route: "LHR-SFO",
    flightNumber: "BA285",
    type: "F",
    date: "Sep 09",
    departure: "11:10",
    arrival: "14:15",
    depStation: "LHR",
    arrStation: "SFO",
    status: "Delayed",
    acType: "B777",
    acReg: "G-STBL",
    groundTime: "2h 45m",
    plan: "Meal Plan A",
    paxTotal: 220,
    pax: {
      first: "8/8",
      business: "48/49",
      premium: "40/40",
      economy: "124/138",
    },
  },
  {
    airlineCode: "LH",
    route: "FRA-DEL",
    flightNumber: "LH760",
    type: "J",
    date: "Sep 10",
    departure: "13:45",
    arrival: "01:30",
    depStation: "FRA",
    arrStation: "DEL",
    status: "Scheduled",
    acType: "B747",
    acReg: "D-ABVP",
    groundTime: "2h 10m",
    plan: "Meal Plan D",
    paxTotal: 340,
    pax: {
      first: "8/8",
      business: "65/67",
      premium: "32/32",
      economy: "235/258",
    },
  },
  {
    airlineCode: "AF",
    route: "CDG-BOM",
    flightNumber: "AF218",
    type: "F",
    date: "Sep 09",
    departure: "10:50",
    arrival: "23:20",
    depStation: "CDG",
    arrStation: "BOM",
    status: "Boarding",
    acType: "A330",
    acReg: "F-GZCN",
    groundTime: "1h 50m",
    plan: "Meal Plan B",
    paxTotal: 205,
    pax: {
      first: "0/0",
      business: "34/36",
      premium: "21/21",
      economy: "150/167",
    },
  },
  {
    airlineCode: "SQ",
    route: "SIN-LAX",
    flightNumber: "SQ38",
    type: "J",
    date: "Sep 10",
    departure: "09:20",
    arrival: "10:10",
    depStation: "SIN",
    arrStation: "LAX",
    status: "On Time",
    acType: "A350",
    acReg: "9V-SJA",
    groundTime: "3h 15m",
    plan: "Meal Plan C",
    paxTotal: 159,
    pax: {
      first: "0/0",
      business: "67/67",
      premium: "92/94",
      economy: "0/0",
    },
  },
  {
    airlineCode: "AI",
    route: "DEL-DXB",
    flightNumber: "AI995",
    type: "J",
    date: "Sep 11",
    departure: "20:00",
    arrival: "22:15",
    depStation: "DEL",
    arrStation: "DXB",
    status: "Scheduled",
    acType: "B787",
    acReg: "VT-ANP",
    groundTime: "1h 30m",
    plan: "Meal Plan E",
    paxTotal: 250,
    pax: {
      first: "0/0",
      business: "18/18",
      premium: "0/0",
      economy: "232/238",
    },
  },
  {
    airlineCode: "6E",
    route: "BOM-BBI",
    flightNumber: "6E2024",
    type: "J",
    date: "Sep 09",
    departure: "05:45",
    arrival: "07:50",
    depStation: "BOM",
    arrStation: "BBI",
    status: "Arrived",
    acType: "A321",
    acReg: "VT-IUA",
    groundTime: "0h 45m",
    plan: "Snack Plan A",
    paxTotal: 222,
    pax: {
      first: "0/0",
      business: "0/0",
      premium: "0/0",
      economy: "222/222",
    },
  },
  {
    airlineCode: "UK",
    route: "DEL-SIN",
    flightNumber: "UK115",
    type: "F",
    date: "Sep 10",
    departure: "23:45",
    arrival: "08:05",
    depStation: "DEL",
    arrStation: "SIN",
    status: "Cancelled",
    acType: "A321",
    acReg: "VT-TVB",
    groundTime: "1h 40m",
    plan: "Meal Plan B",
    paxTotal: 0,
    pax: {
      first: "0/12",
      business: "0/24",
      premium: "0/24",
      economy: "0/128",
    },
  },
  {
    airlineCode: "TK",
    route: "IST-AMS",
    flightNumber: "TK1951",
    type: "J",
    date: "Sep 09",
    departure: "08:35",
    arrival: "11:20",
    depStation: "IST",
    arrStation: "AMS",
    status: "Delayed",
    acType: "B737",
    acReg: "TC-JHL",
    groundTime: "1h 10m",
    plan: "Meal Plan F",
    paxTotal: 145,
    pax: {
      first: "0/0",
      business: "16/16",
      premium: "0/0",
      economy: "129/135",
    },
  },
  {
    airlineCode: "EY",
    route: "AUH-LHR",
    flightNumber: "EY11",
    type: "F",
    date: "Sep 11",
    departure: "02:50",
    arrival: "07:35",
    depStation: "AUH",
    arrStation: "LHR",
    status: "Scheduled",
    acType: "A380",
    acReg: "A6-APA",
    groundTime: "2h 55m",
    plan: "Meal Plan C",
    paxTotal: 480,
    pax: {
      first: "10/11",
      business: "70/70",
      premium: "0/0",
      economy: "400/404",
    },
  },
  {
    airlineCode: "WY",
    route: "MCT-BKK",
    flightNumber: "WY815",
    type: "J",
    date: "Sep 10",
    departure: "21:00",
    arrival: "06:15",
    depStation: "MCT",
    arrStation: "BKK",
    status: "On Time",
    acType: "B787",
    acReg: "A4O-SA",
    groundTime: "1h 55m",
    plan: "Meal Plan A",
    paxTotal: 260,
    pax: {
      first: "0/0",
      business: "30/30",
      premium: "0/0",
      economy: "230/234",
    },
  },
  {
    airlineCode: "EK",
    route: "DXB-CDG",
    flightNumber: "EK073",
    type: "F",
    date: "Sep 09",
    departure: "08:20",
    arrival: "13:30",
    depStation: "DXB",
    arrStation: "CDG",
    status: "Departed",
    acType: "A380",
    acReg: "A6-EOT",
    groundTime: "2h 40m",
    plan: "Meal Plan B",
    paxTotal: 510,
    pax: {
      first: "14/14",
      business: "76/76",
      premium: "50/56",
      economy: "370/379",
    },
  },
  {
    airlineCode: "QR",
    route: "DOH-FRA",
    flightNumber: "QR067",
    type: "J",
    date: "Sep 09",
    departure: "07:55",
    arrival: "13:20",
    depStation: "DOH",
    arrStation: "FRA",
    status: "Arrived",
    acType: "B777",
    acReg: "A7-BEE",
    groundTime: "2h 20m",
    plan: "Meal Plan C",
    paxTotal: 350,
    pax: {
      first: "0/0",
      business: "42/42",
      premium: "0/0",
      economy: "308/312",
    },
  },
  {
    airlineCode: "BA",
    route: "LHR-JFK",
    flightNumber: "BA117",
    type: "F",
    date: "Sep 10",
    departure: "08:25",
    arrival: "11:15",
    depStation: "LHR",
    arrStation: "JFK",
    status: "Scheduled",
    acType: "B777",
    acReg: "G-YMMJ",
    groundTime: "2h 30m",
    plan: "Meal Plan A",
    paxTotal: 270,
    pax: {
      first: "14/14",
      business: "48/48",
      premium: "38/40",
      economy: "170/184",
    },
  },
  {
    airlineCode: "LH",
    route: "FRA-SIN",
    flightNumber: "LH778",
    type: "J",
    date: "Sep 09",
    departure: "22:05",
    arrival: "16:55",
    depStation: "FRA",
    arrStation: "SIN",
    status: "Departed",
    acType: "A380",
    acReg: "D-AIMM",
    groundTime: "3h 05m",
    plan: "Meal Plan D",
    paxTotal: 501,
    pax: {
      first: "8/8",
      business: "78/78",
      premium: "52/52",
      economy: "363/371",
    },
  },
  {
    airlineCode: "AF",
    route: "CDG-DEL",
    flightNumber: "AF226",
    type: "F",
    date: "Sep 10",
    departure: "10:30",
    arrival: "22:40",
    depStation: "CDG",
    arrStation: "DEL",
    status: "Scheduled",
    acType: "B777",
    acReg: "F-GSQI",
    groundTime: "2h 00m",
    plan: "Meal Plan B",
    paxTotal: 290,
    pax: {
      first: "4/4",
      business: "30/35",
      premium: "24/24",
      economy: "232/250",
    },
  },
  {
    airlineCode: "SQ",
    route: "SIN-DXB",
    flightNumber: "SQ494",
    type: "J",
    date: "Sep 09",
    departure: "15:05",
    arrival: "18:25",
    depStation: "SIN",
    arrStation: "DXB",
    status: "On Time",
    acType: "A350",
    acReg: "9V-SMF",
    groundTime: "2h 15m",
    plan: "Meal Plan C",
    paxTotal: 300,
    pax: {
      first: "0/0",
      business: "40/40",
      premium: "0/0",
      economy: "260/263",
    },
  },
  {
    airlineCode: "AI",
    route: "BOM-LHR",
    flightNumber: "AI131",
    type: "J",
    date: "Sep 09",
    departure: "07:00",
    arrival: "12:00",
    depStation: "BOM",
    arrStation: "LHR",
    status: "Cancelled",
    acType: "B777",
    acReg: "VT-ALJ",
    groundTime: "2h 50m",
    plan: "Meal Plan E",
    paxTotal: 0,
    pax: {
      first: "0/8",
      business: "0/35",
      premium: "0/0",
      economy: "0/303",
    },
  },
  {
    airlineCode: "6E",
    route: "DEL-KUL",
    flightNumber: "6E1821",
    type: "J",
    date: "Sep 10",
    departure: "22:50",
    arrival: "07:00",
    depStation: "DEL",
    arrStation: "KUL",
    status: "Boarding",
    acType: "A320",
    acReg: "VT-IFP",
    groundTime: "1h 15m",
    plan: "Snack Plan B",
    paxTotal: 178,
    pax: {
      first: "0/0",
      business: "0/0",
      premium: "0/0",
      economy: "178/180",
    },
  },
  {
    airlineCode: "UK",
    route: "BOM-AUH",
    flightNumber: "UK255",
    type: "F",
    date: "Sep 09",
    departure: "19:30",
    arrival: "21:20",
    depStation: "BOM",
    arrStation: "AUH",
    status: "Departed",
    acType: "A320",
    acReg: "VT-TNI",
    groundTime: "1h 25m",
    plan: "Meal Plan A",
    paxTotal: 150,
    pax: {
      first: "0/0",
      business: "8/8",
      premium: "20/24",
      economy: "122/126",
    },
  },
  {
    airlineCode: "TK",
    route: "IST-SFO",
    flightNumber: "TK79",
    type: "J",
    date: "Sep 10",
    departure: "13:30",
    arrival: "16:55",
    depStation: "IST",
    arrStation: "SFO",
    status: "On Time",
    acType: "B777",
    acReg: "TC-LJJ",
    groundTime: "3h 10m",
    plan: "Meal Plan F",
    paxTotal: 345,
    pax: {
      first: "0/0",
      business: "49/49",
      premium: "0/0",
      economy: "296/300",
    },
  },
  {
    airlineCode: "EY",
    route: "AUH-JFK",
    flightNumber: "EY101",
    type: "F",
    date: "Sep 11",
    departure: "10:10",
    arrival: "16:30",
    depStation: "AUH",
    arrStation: "JFK",
    status: "Scheduled",
    acType: "B787",
    acReg: "A6-BLV",
    groundTime: "3h 20m",
    plan: "Meal Plan C",
    paxTotal: 290,
    pax: {
      first: "8/8",
      business: "28/28",
      premium: "0/0",
      economy: "254/262",
    },
  },
  {
    airlineCode: "QR",
    route: "DOH-LHR",
    flightNumber: "QR007",
    type: "J",
    date: "Sep 09",
    departure: "12:40",
    arrival: "17:55",
    depStation: "DOH",
    arrStation: "LHR",
    status: "Delayed",
    acType: "A380",
    acReg: "A7-APG",
    groundTime: "2h 50m",
    plan: "Meal Plan C",
    paxTotal: 512,
    pax: {
      first: "8/8",
      business: "48/48",
      premium: "0/0",
      economy: "456/461",
    },
  },
  {
    airlineCode: "BA",
    route: "LHR-DXB",
    flightNumber: "BA107",
    type: "F",
    date: "Sep 10",
    departure: "12:45",
    arrival: "22:50",
    depStation: "LHR",
    arrStation: "DXB",
    status: "On Time",
    acType: "B787",
    acReg: "G-ZBKI",
    groundTime: "2h 25m",
    plan: "Meal Plan A",
    paxTotal: 210,
    pax: {
      first: "0/0",
      business: "35/35",
      premium: "50/52",
      economy: "125/127",
    },
  },
  {
    airlineCode: "LH",
    route: "FRA-BOM",
    flightNumber: "LH756",
    type: "J",
    date: "Sep 11",
    departure: "11:05",
    arrival: "23:25",
    depStation: "FRA",
    arrStation: "BOM",
    status: "Scheduled",
    acType: "A340",
    acReg: "D-AIGW",
    groundTime: "1h 45m",
    plan: "Meal Plan D",
    paxTotal: 275,
    pax: {
      first: "0/0",
      business: "42/42",
      premium: "28/28",
      economy: "205/211",
    },
  },
];
